### ISSUE TITLE
Unexpected Activity Errors

### ISSUE THREAD

**Issue by Tangston311** [jimhe/homebridge-infinitude#1]
First, thank you for developing this!  I've been searching for a way to integrate my Bryant thermostat.  I've got Infinitude up and running and working well, but I'm running into a few issues when I install this plugin:

First, I got a number of deprecation errors when I initially installed this.  Not sure what those mean, but thought I would mention it.  I also got an "Unexpected activity for ZONE 1 Thermostat" error when I first launched Homebridge:

![object deprecated warning](https://user-images.githubusercontent.com/47066967/52071904-2d064b80-2541-11e9-939d-f6f9c077de3a.jpg)

![unexpected activity error](https://user-images.githubusercontent.com/47066967/52072059-81a9c680-2541-11e9-9c4d-4428b717359d.jpg)

Second, I can see the thermostat in my Home app and it displays the current temp properly, but when I try to update the temp settings (using Auto mode), I get the following errors in Homebridge and then the temp never actually updates on the thermostat (or in Infinitude):

![unsupported threshold temp errors](https://user-images.githubusercontent.com/47066967/52071995-5f17ad80-2541-11e9-9b6d-9dddd350838f.jpg)

My thermostat is set to a schedule using the Comfort Profiles, so it seems like when I try and change the temperature the plugin can't get the thermostat out of it's current Comfort Profile (and into Manual mode or something), and errors out.

Lastly, just to make sure I have it setup correctly, should the infinitude host in the json file be the ip of my computer running infinitude, or the ip of the infinitude server?

Really appreciate your help. 
Guthrie

**Comment by rcoletti116** [comment]
I have the same problem. Seems that the Home can read the settings, but not update the thermostat. From the update two days ago, this issue still persists, and after updating via Home app the thermostat reads as “No Response.”
I hope this project will allow me to use my Infinity Touch with HomeKit.

**Comment by Tangston311** [comment]
Yeah I tried installing the latest version and encountered the same issue.  The switch appeared, and the thermostat icon appeared in the Home app displaying the correct temperature (but it was in an "off" state and said "Heating to 50" on the icon when the thermostat was actually was on and heating to 71).  By selecting "Auto" as a state in the home app it did actually change the thermostat to a "Home" comfort profile which was progress, but when I tried to change the temp I got the following errors:

<img width="914" alt="screen shot 2019-02-10 at 9 38 36 am" src="https://user-images.githubusercontent.com/47066967/52536465-2e413080-2d18-11e9-8faa-f9fad674d5bb.png">

Still some work to do but glad it's being worked on!

**Comment by johnnylonz** [comment]
I’m having same issue as above. It seems like something isn’t mapped right with the comfort profiles and the commands being sent from homebridge. If I leave my thermostat on “home” and “auto” it at least shows me the current info in HomeKit. But if I change it to “manual” on the thermostat to adjust the temp, it breaks the connection to HomeKit. Likewise, if I try to shush the temp in HomeKit, it errors out in homebridge and then will show the accessory as not responding in HomeKit.

Would love to see this working! I’m not much of a programmer but will help in any way possible.

**Comment by tobylutz** [comment]
The code in InfinitudeThermostat.js is missing thermostat characteristics for the following comfort [sleep, wake, manual] profiles.  

I am not the original developer of this plug-in and my HVAC system isn't fancy enough to require a propriety communication protocol. However, I can certainly create a pull request to try and help fix the issues you're reporting.  

Let me know if there is still a desire to get this working and I'll add this project to my briefcase.

**Comment by Tangston311** [comment]
@tobylutz  yes!  I desire very much.  Thank you!

**Comment by jimhe** [comment]
Hi all, sorry for the confusion. Also, sorry for the delay in this response. I did not realize people were using this plugin!

The current version of this plugin is very simple. The thermostats are only there to show you the temperature and status, but you are not able to control the temperature with them. Alongside each thermostat I have created a switch to toggle the thermostat "on" and "off". When it is turned on, that zone is brought to "home" mode. When it is turned off, it is brought to "away" mode.

I did this because my infinitude set up has historically been very flaky. After a while, it seems that the infinity system stops listening to infinitude's temperature changes. In an effort to make it more stable, I made things a lot simpler. However, it seems that the flakiness is still there. So I would like to bring back temperature control functionality whenever I am able to get around to it.

**Comment by Tangston311** [comment]
FYI, I recently found a HomeAsisstant Component that integrates with Infinitude and is running smoothly so far for anyone interested in going down the HomeAssistant route: [https://github.com/ccalica/homeassistant-infinitude] (this link is a branch of the main repo that fixes an issue with the AUTO setting).

**Comment by jimhe** [comment]
The newest version now supports changing profiles and temperatures with the thermostat accessories. I am closing this for now but it's possible not all the issues have been resolved. Feel free to open new issues for any remaining bugs or requests.
