### ISSUE TITLE
Can't seem to get this to run with Homekit

### ISSUE THREAD

**Issue by swerb73** [jimhe/homebridge-infinitude#10]
I can get it installed through npm, resolved the dependencies, but even after adding the platforms info to the config file HomeKit complains that it can't find the plugin?  Is this a known issue or should I post logs?

**Comment by jimhe** [comment]
Does it work now after latest version?

**Comment by jimhe** [comment]
Please reopen if necessary. Logs would be helpful if you reopen.

**Comment by swerb73** [comment]
Yes, it works now, thank you.
