### ISSUE TITLE
Temperature Setting

### ISSUE THREAD

**Issue by kskenyon** [jimhe/homebridge-infinitude#15]
Can you make it so the temperature set point slider only allows integers like on the thermostat?  Decimals are not useful.

**Comment by jimhe** [comment]
Are you on iOS 12? I believe iOS 13 no longer allows decimals in thermostat.

**Comment by jimhe** [comment]
In any case, this plugin is agnostic to that behavior, it is a HomeKit issue. Closing since I cannot fix it here.
