### ISSUE TITLE
Missing comfort profiles in thermostat characteristics

### ISSUE THREAD

**Issue by tobylutz** [jimhe/homebridge-infinitude#2]
InfinitudeTermostat.js:getTargetHeatingCoolingState(accessory) 
is missing the following targetActivityId's [Sleep, Wake, Manual] profiles.

**Comment by jimhe** [comment]
Unfortunately HomeKit only supports [TargetHeatingCoolingState.[`OFF`, `HEAT`, `COOL`, `AUTO`]](https://github.com/KhaosT/HAP-NodeJS/blob/81319b35d1588453cfcb1a823805643de7df74dc/lib/gen/HomeKitTypes.js#L2342-L2345), which can't map 1:1 to all of Infinitude's profiles. I've decided to make the following mappings:
- `manual` profile to `HEAT` or `COOL` depending on the manual mode set
- `away` profile to `OFF`
- `home` to `AUTO`

See [the code](https://github.com/jimhe/homebridge-infinitude/blob/78c70fe1dd22864efe5da7e5a45401a249d436d9/src/InfinitudeThermostat.js#L241-L255) for more details.
