### ISSUE TITLE
Transfer ownership to dotfortun3-code

### ISSUE THREAD

**Issue by jimhe** [jimhe/homebridge-infinitude#31]

**Comment by jimhe** [comment]
@dotfortun3-code do you have a NPM username?

**Comment by dotfortun3-code** [comment]
> 
> 
> @dotfortun3-code do you have a NPM username?

Sorry for the delay! I do. It's dotfortun3.

**Comment by dotfortun3-code** [comment]
Is there anything I need to do before the repo gets transferred?

**Comment by jimhe** [comment]
@dotfortun3-code I've added you as an owner and maintainer in https://www.npmjs.com/package/homebridge-infinitude

**Comment by jimhe** [comment]
@dotfortun3-code I've updated everything I think that's necessary. You should be able to publish new npm versions yourself. Please let me know if you have any issues.

**Comment by dotfortun3-code** [comment]
@jimhe I just tried a version bump and I do not have write access. I think you can either give me write access, or transfer the ownership of the repo under the settings tab.

**Comment by jimhe** [comment]
Hmm, you are a maintainer with write access...? I also added you as an owner too. What error are you getting exactly?

<img width="801" alt="Screen Shot 2021-05-04 at 8 29 37 AM" src="https://user-images.githubusercontent.com/2302582/117028765-def9c880-acb2-11eb-8e1a-88e4ca2441ef.png">

**Comment by jimhe** [comment]
@dotfortun3-code ^

**Comment by dotfortun3-code** [comment]
No worries, everything is good now. I am just new to this so I had to figure out what I was doing wrong. Thanks!

**Comment by jimhe** [comment]
Glad it's working!
