### ISSUE TITLE
Outdated dependencies hapi

### ISSUE THREAD

**Issue by rcoletti116** [jimhe/homebridge-infinitude#8]
I recently updated and the plugin stopped working. I can't be sure, but it looks like some dependencies are outdated. I have updated the dependencies locally, but it looks like the plugin invokes the deprecated versions directly.

sudo npm i -g homebridge-infinitude@latest
npm WARN deprecated joi@14.3.1: This module has moved and is now available at @hapi/joi. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.

**Comment by jimhe** [comment]
Fixed in 5d75572fff6d84645bcd55026fefeed23fd7f718
